import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "TicTacToe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">      
      <head>
        <meta name="google-signin-client_id" content="322401976875-diq1v37u340lbni1a9q2641a1q47vbq9.apps.googleusercontent.com"></meta>
      </head>
      <body
        className='antialiased bg-background'
      >
        {children}
        <script src="https://accounts.google.com/gsi/client" async /> 
      </body>
    </html>
  );
}
